---

- name: "Get ec2 facts"
  action: ec2_facts

#- name: Set server hostname
#  hostname: name=consul-server-{{ ansible_ec2_local_ipv4|replace('.', '-') }}
#  when: consul_is_server

#- name: Set Client hostname
#  hostname: name=consul-client-{{ ansible_ec2_local_ipv4|replace('.', '-') }}
#  when: not consul_is_server

- name: "Install system packages"
  yum: name={{ item }}
  with_items:
    - dnsmasq

- name: "Download Consul"
  get_url:
    url: https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip
    dest: /tmp/consul.zip

- name: "Download Consul UI"
  get_url:
    url: https://dl.bintray.com/mitchellh/consul/0.5.2_web_ui.zip
    dest: /tmp/consul-ui.zip
  when: consul_is_server

- name: "Unzip Consul binary under /usr/local/bin"
  unarchive: src=/tmp/consul.zip
             dest=/usr/local/bin copy=no

- name: "Create Consul config folder"
  file: path={{ consul_config_dir }} state=directory

- name: "Create Consul data dir"
  file: path={{ consul_data_dir }} mode=755 state=directory

- name: "Create Consul UI dir"
  file: path={{ consul_ui_dir }} mode=755 state=directory
  when: consul_is_server

- name: "Unzip Consul binary under /usr/local/bin"
  unarchive: src=/tmp/consul-ui.zip
             dest={{ consul_ui_dir }} copy=no
  when: consul_is_server

- name: "Create Consul config"
  template: src=consul.j2 dest={{ consul_config_dir }}/consul.json

- name: "Install consul service systemd config"
  template: src=consul-systemd.j2 dest=/etc/systemd/system/consul.service

- name: "enable consul"
  command: sudo systemctl enable consul.service

- name: "restart consul"
  command: sudo systemctl restart consul.service

- name: "Configure Dnsmasq"
  copy: content='server=/consul/127.0.0.1#8600' dest=/etc/dnsmasq.d/10-consul
  when: consul_is_server

- name: "restart dnsmasq"
  service: name=dnsmasq state=restarted enabled=yes
  when: consul_is_server




