---
mesos_version: 0.23.0
mesos_package: "mesos-{{ mesos_version }}"
epel_repo: "http://dl.fedoraproject.org/pub/epel/{{ os_version_major }}/{{ ansible_architecture }}/{{ epel_releases[os_version_major] }}"
mesos_cluster_name: "mesos_cluster1"
mesos_ip: "{{ansible_default_ipv4.address}}"
mesos_hostname: "{{ inventory_hostname }}"
mesos_master_port: "5050"
mesos_slave_port: "5051"
mesos_log_location: "/var/log/mesos"
mesos_ulimit: "-n 8192"
mesos_work_dir: "/var/mesos"
mesos_quorum: "{{ ( groups.control_nodes|count / 2) | round(0, 'ceil') | int }}"
zookeeper_leader_port: "2888"
zookeeper_election_port: "3888"
zookeeper_client_port: "2181"
zookeeper_hostnames: "{{ groups.control_nodes | join(':' + zookeeper_client_port + ',') }}:{{ zookeeper_client_port }}"
mesos_zookeeper_masters: "zk://{{ zookeeper_hostnames }}/mesos"
mesos_masters: "{{ groups.control_nodes | join(':' + mesos_master_port + ',') }}:{{ mesos_master_port }}"
