---
consul_join: "{{ groups['control_nodes'][0]}}"
consul_config_dir: /etc/consul
consul_data_dir: /var/consul/data
consul_ui_dir: /usr/local/bin/ui
consul_advertise: "{{ansible_eth0.ipv4.address}}"
consul_bind: "{{ansible_eth0.ipv4.address}}"
consul_retry_join: "{% for host in groups['control_nodes'] %}\"{{ hostvars[host]['inventory_hostname'] }}\"{% if not loop.last %}, {% endif %}{% endfor %}"
consul_bootstrap_expect: "{{ groups['control_nodes'] | length }}"
