---

- name: "Get ec2 facts"
  action: ec2_facts

- name: "Set SeLinux to permissive"
  selinux: state=disabled

- name: "Install Docker Repository"
  template: src=docker-repo.j2 dest=/etc/yum.repos.d/docker.repo
  when: not consul_is_server

- name: "install docker engine"
  yum: name=docker-engine state=present
  when: not consul_is_server

- name: "Install docker socket systemd config"
  template: src=docker-socket.j2 dest=/etc/systemd/system/docker.socket
  when: not consul_is_server

- name: "Install docker service systemd config"
  template: src=docker-systemd.j2 dest=/etc/systemd/system/docker.service
  when: not consul_is_server

- name: "Install docker dependencies"
  yum: name={{ item }}
  with_items:
      - device-mapper-event-libs
      - python-pip
  when: not consul_is_server

- name: "Install docker-py"
  pip: name=docker-py version=1.4.0

- name: "enable docker"
  service: name=docker enabled=yes
  when: not consul_is_server

- name: "start docker"
  service: name=docker state=started
  when: not consul_is_server

- name: "run registrator container"
  sudo: yes
  docker:
    name: "registrator"
    image: "gliderlabs/registrator:latest"
    pull: "always"
    state: "reloaded"
    restart_policy: "always"
    net: "host"
    volumes: "/var/run/docker.sock:/tmp/docker.sock"
    command: "consul://localhost:8500"
    docker_api_version: 1.18
  when: not consul_is_server
